### ISSUE TITLE
Change build system to poetry-core

### ISSUE THREAD

**Issue by m1kc** [m1kc/notalib#23]
Poetry is compliant with PEP-517, by providing a lightweight core library, so if you use Poetry to manage your Python project you should reference it in the build-system section of the pyproject.toml file like so:

```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

When using the new or init command this section will be automatically added.
If your pyproject.toml file still references poetry directly as a build backend, you should update it to reference poetry-core instead.
